server:
  port: 9020
spring:
  application:
    name: gateway-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 以IP地址注册到服务中心，相互注册使用IP地址
    prefer-ip-address: true